// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockGRPClient is a mock of GRPClient interface.
type MockGRPClient struct {
	ctrl     *gomock.Controller
	recorder *MockGRPClientMockRecorder
}

// MockGRPClientMockRecorder is the mock recorder for MockGRPClient.
type MockGRPClientMockRecorder struct {
	mock *MockGRPClient
}

// NewMockGRPClient creates a new mock instance.
func NewMockGRPClient(ctrl *gomock.Controller) *MockGRPClient {
	mock := &MockGRPClient{ctrl: ctrl}
	mock.recorder = &MockGRPClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGRPClient) EXPECT() *MockGRPClientMockRecorder {
	return m.recorder
}

// CreateBucket mocks base method.
func (m *MockGRPClient) CreateBucket(ctx context.Context, projectID, bucketName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBucket", ctx, projectID, bucketName)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBucket indicates an expected call of CreateBucket.
func (mr *MockGRPClientMockRecorder) CreateBucket(ctx, projectID, bucketName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBucket", reflect.TypeOf((*MockGRPClient)(nil).CreateBucket), ctx, projectID, bucketName)
}

// ReadFile mocks base method.
func (m *MockGRPClient) ReadFile(ctx context.Context, bucketName, objectName string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFile", ctx, bucketName, objectName)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile.
func (mr *MockGRPClientMockRecorder) ReadFile(ctx, bucketName, objectName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*MockGRPClient)(nil).ReadFile), ctx, bucketName, objectName)
}

// UploadDirectory mocks base method.
func (m *MockGRPClient) UploadDirectory(ctx context.Context, projectID, bucketName, destinationDir, sourcePath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadDirectory", ctx, projectID, bucketName, destinationDir, sourcePath)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadDirectory indicates an expected call of UploadDirectory.
func (mr *MockGRPClientMockRecorder) UploadDirectory(ctx, projectID, bucketName, destinationDir, sourcePath interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadDirectory", reflect.TypeOf((*MockGRPClient)(nil).UploadDirectory), ctx, projectID, bucketName, destinationDir, sourcePath)
}

// UploadFile mocks base method.
func (m *MockGRPClient) UploadFile(ctx context.Context, projectID, bucketName, objectName, filePath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", ctx, projectID, bucketName, objectName, filePath)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockGRPClientMockRecorder) UploadFile(ctx, projectID, bucketName, objectName, filePath interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockGRPClient)(nil).UploadFile), ctx, projectID, bucketName, objectName, filePath)
}
