// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by MockGen. DO NOT EDIT.
// Source: artifactregistryiface/interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	artifactregistryiface "devops-mcp-server/artifactregistryiface"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	artifactregistry "google.golang.org/genproto/googleapis/devtools/artifactregistry/v1"
)

// MockCreateRepositoryOperation is a mock of CreateRepositoryOperation interface.
type MockCreateRepositoryOperation struct {
	ctrl     *gomock.Controller
	recorder *MockCreateRepositoryOperationMockRecorder
}

// MockCreateRepositoryOperationMockRecorder is the mock recorder for MockCreateRepositoryOperation.
type MockCreateRepositoryOperationMockRecorder struct {
	mock *MockCreateRepositoryOperation
}

// NewMockCreateRepositoryOperation creates a new mock instance.
func NewMockCreateRepositoryOperation(ctrl *gomock.Controller) *MockCreateRepositoryOperation {
	mock := &MockCreateRepositoryOperation{ctrl: ctrl}
	mock.recorder = &MockCreateRepositoryOperationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateRepositoryOperation) EXPECT() *MockCreateRepositoryOperationMockRecorder {
	return m.recorder
}

// Wait mocks base method.
func (m *MockCreateRepositoryOperation) Wait(arg0 context.Context) (*artifactregistry.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wait", arg0)
	ret0, _ := ret[0].(*artifactregistry.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Wait indicates an expected call of Wait.
func (mr *MockCreateRepositoryOperationMockRecorder) Wait(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wait", reflect.TypeOf((*MockCreateRepositoryOperation)(nil).Wait), arg0)
}

// MockGRPClient is a mock of GRPClient interface.
type MockGRPClient struct {
	ctrl     *gomock.Controller
	recorder *MockGRPClientMockRecorder
}

// MockGRPClientMockRecorder is the mock recorder for MockGRPClient.
type MockGRPClientMockRecorder struct {
	mock *MockGRPClient
}

// NewMockGRPClient creates a new mock instance.
func NewMockGRPClient(ctrl *gomock.Controller) *MockGRPClient {
	mock := &MockGRPClient{ctrl: ctrl}
	mock.recorder = &MockGRPClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGRPClient) EXPECT() *MockGRPClientMockRecorder {
	return m.recorder
}

// CreateRepository mocks base method.
func (m *MockGRPClient) CreateRepository(arg0 context.Context, arg1 *artifactregistry.CreateRepositoryRequest) (artifactregistryiface.CreateRepositoryOperation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRepository", arg0, arg1)
	ret0, _ := ret[0].(artifactregistryiface.CreateRepositoryOperation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRepository indicates an expected call of CreateRepository.
func (mr *MockGRPClientMockRecorder) CreateRepository(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRepository", reflect.TypeOf((*MockGRPClient)(nil).CreateRepository), arg0, arg1)
}