// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	cloudbuildiface "devops-mcp-server/cloudbuildiface"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	cloudbuild "google.golang.org/api/cloudbuild/v1"
	googleapi "google.golang.org/api/googleapi"
)

// MockBuildsCreateCallAPI is a mock of BuildsCreateCallAPI interface.
type MockBuildsCreateCallAPI struct {
	ctrl     *gomock.Controller
	recorder *MockBuildsCreateCallAPIMockRecorder
}

// MockBuildsCreateCallAPIMockRecorder is the mock recorder for MockBuildsCreateCallAPI.
type MockBuildsCreateCallAPIMockRecorder struct {
	mock *MockBuildsCreateCallAPI
}

// NewMockBuildsCreateCallAPI creates a new mock instance.
func NewMockBuildsCreateCallAPI(ctrl *gomock.Controller) *MockBuildsCreateCallAPI {
	mock := &MockBuildsCreateCallAPI{ctrl: ctrl}
	mock.recorder = &MockBuildsCreateCallAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuildsCreateCallAPI) EXPECT() *MockBuildsCreateCallAPIMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockBuildsCreateCallAPI) Context(arg0 context.Context) cloudbuildiface.BuildsCreateCallAPI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context", arg0)
	ret0, _ := ret[0].(cloudbuildiface.BuildsCreateCallAPI)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockBuildsCreateCallAPIMockRecorder) Context(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockBuildsCreateCallAPI)(nil).Context), arg0)
}

// Do mocks base method.
func (m *MockBuildsCreateCallAPI) Do(opts ...googleapi.CallOption) (*cloudbuild.Operation, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Do", varargs...)
	ret0, _ := ret[0].(*cloudbuild.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockBuildsCreateCallAPIMockRecorder) Do(opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockBuildsCreateCallAPI)(nil).Do), opts...)
}

// MockBuildsServiceAPI is a mock of BuildsServiceAPI interface.
type MockBuildsServiceAPI struct {
	ctrl     *gomock.Controller
	recorder *MockBuildsServiceAPIMockRecorder
}

// MockBuildsServiceAPIMockRecorder is the mock recorder for MockBuildsServiceAPI.
type MockBuildsServiceAPIMockRecorder struct {
	mock *MockBuildsServiceAPI
}

// NewMockBuildsServiceAPI creates a new mock instance.
func NewMockBuildsServiceAPI(ctrl *gomock.Controller) *MockBuildsServiceAPI {
	mock := &MockBuildsServiceAPI{ctrl: ctrl}
	mock.recorder = &MockBuildsServiceAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuildsServiceAPI) EXPECT() *MockBuildsServiceAPIMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBuildsServiceAPI) Create(parent string, build *cloudbuild.Build) cloudbuildiface.BuildsCreateCallAPI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", parent, build)
	ret0, _ := ret[0].(cloudbuildiface.BuildsCreateCallAPI)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBuildsServiceAPIMockRecorder) Create(parent, build interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBuildsServiceAPI)(nil).Create), parent, build)
}

// MockTriggersCreateCallAPI is a mock of TriggersCreateCallAPI interface.
type MockTriggersCreateCallAPI struct {
	ctrl     *gomock.Controller
	recorder *MockTriggersCreateCallAPIMockRecorder
}

// MockTriggersCreateCallAPIMockRecorder is the mock recorder for MockTriggersCreateCallAPI.
type MockTriggersCreateCallAPIMockRecorder struct {
	mock *MockTriggersCreateCallAPI
}

// NewMockTriggersCreateCallAPI creates a new mock instance.
func NewMockTriggersCreateCallAPI(ctrl *gomock.Controller) *MockTriggersCreateCallAPI {
	mock := &MockTriggersCreateCallAPI{ctrl: ctrl}
	mock.recorder = &MockTriggersCreateCallAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTriggersCreateCallAPI) EXPECT() *MockTriggersCreateCallAPIMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockTriggersCreateCallAPI) Context(arg0 context.Context) cloudbuildiface.TriggersCreateCallAPI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context", arg0)
	ret0, _ := ret[0].(cloudbuildiface.TriggersCreateCallAPI)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockTriggersCreateCallAPIMockRecorder) Context(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockTriggersCreateCallAPI)(nil).Context), arg0)
}

// Do mocks base method.
func (m *MockTriggersCreateCallAPI) Do(opts ...googleapi.CallOption) (*cloudbuild.BuildTrigger, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Do", varargs...)
	ret0, _ := ret[0].(*cloudbuild.BuildTrigger)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockTriggersCreateCallAPIMockRecorder) Do(opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockTriggersCreateCallAPI)(nil).Do), opts...)
}

// MockTriggersRunCallAPI is a mock of TriggersRunCallAPI interface.
type MockTriggersRunCallAPI struct {
	ctrl     *gomock.Controller
	recorder *MockTriggersRunCallAPIMockRecorder
}

// MockTriggersRunCallAPIMockRecorder is the mock recorder for MockTriggersRunCallAPI.
type MockTriggersRunCallAPIMockRecorder struct {
	mock *MockTriggersRunCallAPI
}

// NewMockTriggersRunCallAPI creates a new mock instance.
func NewMockTriggersRunCallAPI(ctrl *gomock.Controller) *MockTriggersRunCallAPI {
	mock := &MockTriggersRunCallAPI{ctrl: ctrl}
	mock.recorder = &MockTriggersRunCallAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTriggersRunCallAPI) EXPECT() *MockTriggersRunCallAPIMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockTriggersRunCallAPI) Context(arg0 context.Context) cloudbuildiface.TriggersRunCallAPI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context", arg0)
	ret0, _ := ret[0].(cloudbuildiface.TriggersRunCallAPI)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockTriggersRunCallAPIMockRecorder) Context(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockTriggersRunCallAPI)(nil).Context), arg0)
}

// Do mocks base method.
func (m *MockTriggersRunCallAPI) Do(opts ...googleapi.CallOption) (*cloudbuild.Operation, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Do", varargs...)
	ret0, _ := ret[0].(*cloudbuild.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockTriggersRunCallAPIMockRecorder) Do(opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockTriggersRunCallAPI)(nil).Do), opts...)
}

// MockTriggersListCallAPI is a mock of TriggersListCallAPI interface.
type MockTriggersListCallAPI struct {
	ctrl     *gomock.Controller
	recorder *MockTriggersListCallAPIMockRecorder
}

// MockTriggersListCallAPIMockRecorder is the mock recorder for MockTriggersListCallAPI.
type MockTriggersListCallAPIMockRecorder struct {
	mock *MockTriggersListCallAPI
}

// NewMockTriggersListCallAPI creates a new mock instance.
func NewMockTriggersListCallAPI(ctrl *gomock.Controller) *MockTriggersListCallAPI {
	mock := &MockTriggersListCallAPI{ctrl: ctrl}
	mock.recorder = &MockTriggersListCallAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTriggersListCallAPI) EXPECT() *MockTriggersListCallAPIMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockTriggersListCallAPI) Context(arg0 context.Context) cloudbuildiface.TriggersListCallAPI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context", arg0)
	ret0, _ := ret[0].(cloudbuildiface.TriggersListCallAPI)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockTriggersListCallAPIMockRecorder) Context(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockTriggersListCallAPI)(nil).Context), arg0)
}

// Do mocks base method.
func (m *MockTriggersListCallAPI) Do(opts ...googleapi.CallOption) (*cloudbuild.ListBuildTriggersResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Do", varargs...)
	ret0, _ := ret[0].(*cloudbuild.ListBuildTriggersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockTriggersListCallAPIMockRecorder) Do(opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockTriggersListCallAPI)(nil).Do), opts...)
}

// MockTriggersServiceAPI is a mock of TriggersServiceAPI interface.
type MockTriggersServiceAPI struct {
	ctrl     *gomock.Controller
	recorder *MockTriggersServiceAPIMockRecorder
}

// MockTriggersServiceAPIMockRecorder is the mock recorder for MockTriggersServiceAPI.
type MockTriggersServiceAPIMockRecorder struct {
	mock *MockTriggersServiceAPI
}

// NewMockTriggersServiceAPI creates a new mock instance.
func NewMockTriggersServiceAPI(ctrl *gomock.Controller) *MockTriggersServiceAPI {
	mock := &MockTriggersServiceAPI{ctrl: ctrl}
	mock.recorder = &MockTriggersServiceAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTriggersServiceAPI) EXPECT() *MockTriggersServiceAPIMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTriggersServiceAPI) Create(parent string, buildtrigger *cloudbuild.BuildTrigger) cloudbuildiface.TriggersCreateCallAPI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", parent, buildtrigger)
	ret0, _ := ret[0].(cloudbuildiface.TriggersCreateCallAPI)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTriggersServiceAPIMockRecorder) Create(parent, buildtrigger interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTriggersServiceAPI)(nil).Create), parent, buildtrigger)
}

// List mocks base method.
func (m *MockTriggersServiceAPI) List(parent string) cloudbuildiface.TriggersListCallAPI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", parent)
	ret0, _ := ret[0].(cloudbuildiface.TriggersListCallAPI)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockTriggersServiceAPIMockRecorder) List(parent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTriggersServiceAPI)(nil).List), parent)
}

// Run mocks base method.
func (m *MockTriggersServiceAPI) Run(name string, runbuildtriggerrequest *cloudbuild.RunBuildTriggerRequest) cloudbuildiface.TriggersRunCallAPI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", name, runbuildtriggerrequest)
	ret0, _ := ret[0].(cloudbuildiface.TriggersRunCallAPI)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockTriggersServiceAPIMockRecorder) Run(name, runbuildtriggerrequest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockTriggersServiceAPI)(nil).Run), name, runbuildtriggerrequest)
}

// MockOperationsGetCallAPI is a mock of OperationsGetCallAPI interface.
type MockOperationsGetCallAPI struct {
	ctrl     *gomock.Controller
	recorder *MockOperationsGetCallAPIMockRecorder
}

// MockOperationsGetCallAPIMockRecorder is the mock recorder for MockOperationsGetCallAPI.
type MockOperationsGetCallAPIMockRecorder struct {
	mock *MockOperationsGetCallAPI
}

// NewMockOperationsGetCallAPI creates a new mock instance.
func NewMockOperationsGetCallAPI(ctrl *gomock.Controller) *MockOperationsGetCallAPI {
	mock := &MockOperationsGetCallAPI{ctrl: ctrl}
	mock.recorder = &MockOperationsGetCallAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOperationsGetCallAPI) EXPECT() *MockOperationsGetCallAPIMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockOperationsGetCallAPI) Context(arg0 context.Context) cloudbuildiface.OperationsGetCallAPI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context", arg0)
	ret0, _ := ret[0].(cloudbuildiface.OperationsGetCallAPI)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockOperationsGetCallAPIMockRecorder) Context(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockOperationsGetCallAPI)(nil).Context), arg0)
}

// Do mocks base method.
func (m *MockOperationsGetCallAPI) Do(opts ...googleapi.CallOption) (*cloudbuild.Operation, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Do", varargs...)
	ret0, _ := ret[0].(*cloudbuild.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockOperationsGetCallAPIMockRecorder) Do(opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockOperationsGetCallAPI)(nil).Do), opts...)
}

// MockOperationsServiceAPI is a mock of OperationsServiceAPI interface.
type MockOperationsServiceAPI struct {
	ctrl     *gomock.Controller
	recorder *MockOperationsServiceAPIMockRecorder
}

// MockOperationsServiceAPIMockRecorder is the mock recorder for MockOperationsServiceAPI.
type MockOperationsServiceAPIMockRecorder struct {
	mock *MockOperationsServiceAPI
}

// NewMockOperationsServiceAPI creates a new mock instance.
func NewMockOperationsServiceAPI(ctrl *gomock.Controller) *MockOperationsServiceAPI {
	mock := &MockOperationsServiceAPI{ctrl: ctrl}
	mock.recorder = &MockOperationsServiceAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOperationsServiceAPI) EXPECT() *MockOperationsServiceAPIMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockOperationsServiceAPI) Get(name string) cloudbuildiface.OperationsGetCallAPI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", name)
	ret0, _ := ret[0].(cloudbuildiface.OperationsGetCallAPI)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockOperationsServiceAPIMockRecorder) Get(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockOperationsServiceAPI)(nil).Get), name)
}
